### ISSUE TITLE
Uncaught exception 'Symfony\Component\Process\Exception\RuntimeException' with message 'The process has been signaled with signal "11".' in /Applications/XAMPP/xamppfiles/htdocs/shoutoutbot/vendor/symfony/process/Process.php:370 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/shoutoutbot/vendor/symfony/process/Process.php(202): Symfony\Component\Process\Process->wait() #1 /Applications/XAMPP/xamppfiles/htdocs/shoutoutbot/vendor/symfony/process/Process.php(224): Symfony\Component\Process\Process->run(NULL) #2 /Applications/XAMPP/xamppfiles/htdocs/shoutoutbot/vendor/lukaswhite/screenshotter/src/Lukaswhite/Screenshotter/Screenshotter.php(226): Symfony\Component\Process\Process->mustRun() #3 /Applications/XAMPP/xamppfiles/htdocs/shoutoutbot/index.php(52): Lukaswhite\Screenshotter\Screenshotter->capture('https://www.you...', 'test1499005691p...', Array) #4 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/shoutoutbot/vendor/symfony/process/Process.php on line 370

### ISSUE THREAD

**Issue by EthanSK** [lukaswhite/screenshotter#4]
Uncaught exception 'Symfony\Component\Process\Exception\RuntimeException' with message 'The process has been signaled with signal "11".' in /Applications/XAMPP/xamppfiles/htdocs/shoutoutbot/vendor/symfony/process/Process.php:370 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/shoutoutbot/vendor/symfony/process/Process.php(202): Symfony\Component\Process\Process->wait() #1 /Applications/XAMPP/xamppfiles/htdocs/shoutoutbot/vendor/symfony/process/Process.php(224): Symfony\Component\Process\Process->run(NULL) #2 /Applications/XAMPP/xamppfiles/htdocs/shoutoutbot/vendor/lukaswhite/screenshotter/src/Lukaswhite/Screenshotter/Screenshotter.php(226): Symfony\Component\Process\Process->mustRun() #3 /Applications/XAMPP/xamppfiles/htdocs/shoutoutbot/index.php(52): Lukaswhite\Screenshotter\Screenshotter->capture('https://www.you...', 'test1499005691p...', Array) #4 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/shoutoutbot/vendor/symfony/process/Process.php on line 370

**Comment by EthanSK** [comment]
please fix this i need it
